import AppKit
import os.log

private let logger = Logger(subsystem: "com.clipflow", category: "ClipboardMonitor")

final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let onChange: (ClipItem) -> Void
    private let processingQueue = DispatchQueue(label: "com.clipflow.image-processing", qos: .userInitiated)

    // Transient/concealed pasteboard types (password managers, OTPs)
    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(onChange: @escaping (ClipItem) -> Void) {
        self.onChange = onChange
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.check()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount

        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        guard let types = pasteboard.types else { return }
        let typeStrings = Set(types.map(\.rawValue))

        // Step 1: Skip transient/concealed content (passwords, OTPs)
        if !Self.transientTypes.isDisjoint(with: typeStrings) {
            logger.info("Skipping transient/concealed pasteboard content")
            return
        }

        let frontApp = NSWorkspace.shared.frontmostApplication
        let sourceApp = frontApp?.localizedName

        // Step 2: Check for image data (priority: tiff > png > jpeg)
        if let imageData = readImageData(from: pasteboard, types: types) {
            processingQueue.async { [weak self] in
                guard let result = ImageProcessor.processImage(from: imageData) else {
                    logger.warning("Image processing failed, skipping")
                    return
                }

                let item = ClipItem(
                    content: .image(result.pngData, thumbnail: result.thumbnail, size: result.size),
                    timestamp: Date(),
                    sourceApp: sourceApp
                )
                self?.onChange(item)
            }
            return
        }

        // Step 3: Fall back to text
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            let item = ClipItem(
                content: .text(string),
                timestamp: Date(),
                sourceApp: sourceApp
            )
            onChange(item)
        }
    }

    private func readImageData(from pasteboard: NSPasteboard, types: [NSPasteboard.PasteboardType]) -> Data? {
        let imageTypes: [NSPasteboard.PasteboardType] = [
            .tiff,
            .png,
            NSPasteboard.PasteboardType("public.jpeg"),
        ]

        for type in imageTypes {
            if types.contains(type), let data = pasteboard.data(forType: type) {
                return data
            }
        }
        return nil
    }
}
